# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80f457590bb139bf63c7665eb3c6ee356135407ebfb3a77dc4ac182bc023479fa6fab132b0e7633246b0a18185b1efdda8fe8f40dcc07387d89a5fab153f27bc

test:
  secret_key_base: 6ace656243f050c47d2ec91a720b2cc0f3787e3887fe8b82d33b2005f802dfc0eb1e14ba9ac6bafe95a06675c74bba5db91058b2194b578754f936cd6f1657bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 6367ddf7f9ad1de21206ff135e448411406ac20d28998743920c8893b9415cb58cfd67b3a7c6d8a778de738f5489e2291006d0aaed61b3b7b5c5c147e2174729
